image: $helm_registry_image:$helm_registry_version

variables:
  registry: quay.io
  registry_user: samsung_cnct
  chart_name: fluent-bit
  robot_account: fluent_bit_rw
  helm_registry_image: quay.io/samsung_cnct/helm-registry-agent
  helm_registry_version: v0.1.5

stages:
  - build
  - test
  - publish

before_script:
  - helm registry login -u ${registry_user}+${robot_account} -p ${REGISTRY_PASSWORD} ${registry}

build_chart:
  stage: build
  script:
    - sh build/build.sh

build_foo:
  stage: build
  script:
    - echo "I'm a little teapot"

helm_test:
  stage: test
  script:
    - sh build/test.sh

helm_publish:
  stage: publish
  script:
    - cd ${chart_name} && helm registry push ${registry}/${registry_user}/${chart_name} -c alpha