---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{.Values.name}}
  labels:
    app: {{ template "name" . }}
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{.Values.name}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        {{- if .Values.tolerations }}
        tolerations: 
        {{- range .Values.tolerations }}
        - key: {{ .key | default("")}}
          value: {{ .value | default("")}}
          operator: {{ .operator | default("")}}
          effect: {{ .effect | default("")}}
        {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
