# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: fluent-bit
image: quay.io/samsung_cnct/fluent-bit-container:latest

#  example toleration
#tolerations:
#  - key: taintKey
#    value: taintValue
#    operator: Equal
#    effect: NoSchedule
