---
name: fluent-bit
image: quay.io/samsung_cnct/fluent-bit-container:prod

cluster_uuid: 00000000-0000-0000-0000-000000000000

resources:
  requests:
    cpu: 100m
    mem: 500Mi
  limits:
    cpu: 300m
    mem: 1000Mi

elasticSearchHost: elasticsearch
elasticSearchPort: 9200

# Path to directory containing `journald/` and `containers/`, typically
# `/var/log/`, though some operating systems store logs in `/run/log`. Cf.
# https://goo.gl/apMdJY and https://goo.gl/WaHSNf
varLogPath: /var/log

#config: |-

#parsers: |-
